---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Frontside's Backstage Developer Portal
  annotations:
    github.com/project-slug: thefrontside/backstage
    "humanitec.com/orgId": "the-frontside-software-inc"
    "humanitec.com/appId": "backstage"
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: thefrontside/staff
  lifecycle: production
