---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: MCK Backstage Developer Portal
  # Example for optional annotations
  annotations:
    github.com/project-slug: humanitec/backstage-demo
    "humanitec.com/orgId": "mck-poc"
    "humanitec.com/appId": "backstage"
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: engine@humanitec.com
  lifecycle: production
