apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: {{ required "You must provide a Postgres username" .Values.postgresUsername }}
  POSTGRES_PASSWORD: {{ required "You must provide a Postgres username" .Values.postgresPassword }}
