apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 2
  progressDeadlineSeconds: 35
    # 15 initial of startup probe + 15 (5 period x 3) + 5 leeway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: {{ required "You must provide a Backstage image" .Values.backstageImage }}
        command: ["node", "packages/backend", "--config", "app-config.yaml"]
        ports:
          - name: http
            containerPort: {{ .Values.backstagePort | default 7007 }}
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: http
        startupProbe:
          httpGet:
            path: /api/healthcheck
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
          - name: APP_CONFIG_app_baseUrl
            value: {{ .Values.baseUrl }}
          - name: APP_CONFIG_backend_baseUrl
            value: {{ .Values.baseUrl }}
        envFrom:
          - secretRef:
              name: postgres-secrets
