apiVersion: v1
kind: Service
metadata:
  name: backstage-loadbalancer
spec:
  selector:
    app: backstage
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.loadBalancerPort | default 80 }} # port that is exposed to the outside
    targetPort: {{ .Values.backstagePort | default 7007 }} # port of backstage app within the cluster
