apiVersion: v1
kind: Secret
metadata:
  name: backstage-credentials
data:
  backstage-app-credentials.yaml: {{ required "You must provide credentials for the Github Frontside Backstage App" .Values.backstageGithubCredentials }}
