apiVersion: v1
kind: Service
metadata:
  name: backstage
spec:
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: {{ .Values.ingressPort | default 80 }}
      targetPort: {{ .Values.backstagePort | default 7007 }}
