apiVersion: v1
kind: Service
metadata:
  name: backstage-loadbalancer
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # port that is exposed to the outside
    targetPort: 7007 # port of backstage app within the cluster
