name: Build and Test

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - run: yarn install --frozen-lockfile # optional, --immutable
  
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - run: yarn build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: yarn test