name: Backstage Release

on: push

concurrency: ${{ github.ref }}

env:
  IMAGE: "northamerica-northeast1-docker.pkg.dev/frontside-backstage/frontside-artifacts/backstage"
  CLUSTER: "backstage-cluster"
  ZONE: "northamerica-northeast1-a"

jobs:
  release:
    name: Cloud Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.CLOUD_WORKLOAD_PROVIDER}}
        service_account: ${{ secrets.CLOUD_SERVICE_ACCOUNT }}
    - name: gcloud sdk
      uses: google-github-actions/setup-gcloud@v0
    - run: yarn && yarn tsc && yarn build
    # - run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-6`" >> $GITHUB_ENV
    # - run: gcloud builds submit . --config=cloudbuild.yaml --substitutions=_IMAGE="$IMAGE:$TAG"
    - run: gcloud container clusters get-credentials $CLUSTER --zone $ZONE
    - run: kubectl get all
