name: Backstage Release

on: push

jobs:
  release:
    name: Cloud Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.CLOUD_WORKLOAD_PROVIDER}}
        service_account: ${{ secrets.CLOUD_SERVICE_ACCOUNT }}
    - name: gcloud sdk
      uses: google-github-actions/setup-gcloud@v0
    - run: gcloud info
